#!/usr/bin/env bash
set -euo pipefail

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

bash -n "$ROOT/install.sh"
bash -n "$ROOT/uninstall.sh"
bash -n "$ROOT/status.sh"
bash -n "$ROOT/manage.sh"
bash -n "$ROOT/install-oneclick.sh"
bash -n "$ROOT/iptv-routeros-sync"
bash -n "$ROOT/update.sh"

installer_version=$(cat "$ROOT/VERSION")
oneclick_version=$(sed -n 's/^VERSION="\([^"]*\)"$/\1/p' "$ROOT/install-oneclick.sh")
test "$installer_version" = "$oneclick_version"

grep -q 'INSTALL_DIR="${WORK_DIR}/app"' "$ROOT/install-oneclick.sh"
grep -q 'if \[ ! -f "${INSTALL_DIR}/install.sh" \]' "$ROOT/install-oneclick.sh"
grep -q 'for mysql_account_host in localhost 127.0.0.1 %' "$ROOT/install.sh"
grep -q '检测到现有安装' "$ROOT/install.sh"
grep -q '覆盖安装必须重新抓包机顶盒' "$ROOT/install.sh"
grep -q 'ROUTEROS_IPTV_DHCP_IP' "$ROOT/install.sh"
grep -q 'in_stb && /^  uid:/' "$ROOT/install.sh"
grep -q 'address %s/16' "$ROOT/install.sh"
grep -q '124.75.0.0/16' "$ROOT/install.sh"
grep -q 'via %s dev eth1 src %s' "$ROOT/install.sh"
grep -q 'upgrade-backup' "$ROOT/install.sh"
grep -q 'iptv-spider-uninstall' "$ROOT/install.sh"
grep -q 'iptv-spider-status' "$ROOT/install.sh"
grep -q 'APP_DIR/manage.sh' "$ROOT/install.sh"
grep -q '手动抓取' "$ROOT/manage.sh"
grep -q '服务保持运行' "$ROOT/manage.sh"
grep -q "echo '  4、抓取计划'" "$ROOT/manage.sh"
grep -q "echo '  5、卸载'" "$ROOT/manage.sh"
grep -q '4) edit_fetch_schedule' "$ROOT/manage.sh"
grep -q 'config.yaml.schedule-backup' "$ROOT/manage.sh"
grep -q 'fetch_cron:' "$ROOT/manage.sh"
grep -q '频道信息列表更新完成' "$ROOT/manage.sh"
grep -q '更新节目信息列表完成' "$ROOT/manage.sh"
grep -q 'tail -c' "$ROOT/manage.sh"
grep -q 'stat -Lc %s' "$ROOT/manage.sh"
grep -q 'default-character-set=utf8mb4' "$ROOT/status.sh"
grep -q 'LC_ALL=C.UTF-8' "$ROOT/status.sh"
grep -q '"/tv.m3u"' "$ROOT/router/router.go"
grep -q '"/tv-direct.m3u"' "$ROOT/router/router.go"
grep -q '"/iptvsharp.m3u"' "$ROOT/router/router.go"
grep -q 'days := configuredCatchupDays()' "$ROOT/router/api/router.go"
grep -q 'boundary := epgHistoryBoundary(time.Now(), daysAgo)' "$ROOT/modules/auth/generate.go"
grep -q 'Where("start_time >= ?", boundary)' "$ROOT/modules/auth/generate.go"
grep -q 'return name + "【已过期】"' "$ROOT/modules/auth/epg_window.go"
grep -q '通用播放源.*tv.m3u' "$ROOT/install.sh"
grep -q 'IPTV# 专用播放源.*iptvsharp.m3u' "$ROOT/install.sh"
grep -q 'install_routeros_sync' "$ROOT/install.sh"
grep -q 'bridge_iptv' "$ROOT/iptv-routeros-sync"
grep -q 'iptv-spider CT EPG SNAT' "$ROOT/iptv-routeros-sync"
test -f "$ROOT/systemd/iptv-routeros-sync.service"
test -f "$ROOT/systemd/iptv-routeros-sync.timer"
grep -q 'install_update_units' "$ROOT/install.sh"
grep -q 'iptv-spider-update.timer' "$ROOT/install.sh"
grep -q 'iptv-spider-update.timer' "$ROOT/../install-dhcp.sh"
grep -q 'disable --now iptv-spider-update.timer' "$ROOT/uninstall.sh"
grep -q 'rm -f /usr/local/sbin/iptv-spider-update' "$ROOT/uninstall.sh"
grep -q "echo '  6、检查更新'" "$ROOT/manage.sh"
grep -q "echo '  7、自动更新设置'" "$ROOT/manage.sh"
grep -q '6) update_menu' "$ROOT/manage.sh"
grep -q '7) auto_update_menu' "$ROOT/manage.sh"
grep -q 'update-state' "$ROOT/status.sh"
grep -q 'api.github.com' "$ROOT/update.sh"
grep -q 'sha256sum -c' "$ROOT/update.sh"
grep -q 'update-backup' "$ROOT/update.sh"
grep -q 'restore_backup' "$ROOT/update.sh"
test -f "$ROOT/systemd/iptv-spider-update.service"
test -f "$ROOT/systemd/iptv-spider-update.timer"
test -f "$ROOT/update.conf.example"
test -x "$ROOT/update.sh"
test -x "$ROOT/tests/update_logic_test.sh"

test -x "$ROOT/install.sh"
test -x "$ROOT/uninstall.sh"
test -x "$ROOT/status.sh"
test -x "$ROOT/manage.sh"
test -x "$ROOT/bin/iptv-spider-linux-amd64"
test -x "$ROOT/bin/stb-probe-linux-amd64"
test -f "$ROOT/assets/channel-reference.m3u"
test -f "$ROOT/assets/logos/CGTN.png"

echo 'installer static checks passed'
